# Generated by Django 5.1.1 on 2024-09-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
